import assert from 'node:assert/strict';import fs from 'node:fs';
import {migrate,profileSchema,accountSchema,makePlan,byId,exercises,equipment,alternatives,eligible,nutrition,chooseDays,goals,areas,prTypes,loadAdvice,plateTotal,plateSolve,adherence,comebackDue,localDate,sessionSchema,injuryCardioMap} from '../lib/fitness';import{mealPlan}from'../lib/meals';import{localState,KEY}from'../local-state';
const results:any[]=[];const check=(name:string,fn:()=>void)=>{fn();results.push({name,status:'passed'});console.log('PASS',name)};
const oldProfile={id:'qa',name:'Synthetic QA',age:30,birthDate:'',weight:70,height:175,measuredAt:'2026-09-19',goal:'muscle',experience:'beginner',days:[0,1,3,5],minutes:45,equipment:['machine','cable','dumbbell','barbell','cardio'],priority:'balanced',health:'none',restrictions:'',sex:'male',activity:'low',sleep:7,diet:'mixed',allergies:'',split:'upper',stage:0,createdAt:'2026-09-19',nutritionEnabled:true,rehab:'Original therapist free text'};
const a=migrate({profiles:[{profile:oldProfile,sessions:[],reports:[]}],activeId:'qa'});const p=a.profiles[0].profile;
check('Old profile migration preserves days, free-text rehab, identity and defaults',()=>{assert.deepEqual(p.days,oldProfile.days);assert.deepEqual(p.availableDays,p.days);assert.equal(p.sessionsPerWeek,4);assert.equal(p.rehab,oldProfile.rehab);assert.deepEqual(p.injuries,[]);assert.deepEqual(migrate(a),a)});
check('108 unique exercises, old IDs preserved, two assets each, area tags and aliases',()=>{assert.equal(exercises.length,108);assert.equal(new Set(exercises.map(e=>e.id)).size,108);for(const e of exercises){assert(e.loadedAreas?.length);assert(e.aliases?.length);for(const n of [0,1])assert(fs.existsSync(`public/exercises/${e.id}-${n}.webp`))}});
check('3 sessions selected only from 5 available days',()=>{const d=chooseDays([0,1,2,4,6],3,6);assert.equal(d.length,3);assert(d.every(x=>[0,1,2,4,6].includes(x)))});
check('Conservative injury / unknown plan; active areas excluded from plans and swaps',()=>{for(const h of ['injury','unknown']as const){const q={...p,health:h,injuries:[{area:'knee' as const,status:'active' as const,reportedAt:'2026-09-29',reviewed:false,history:[]}]};const plan=makePlan(q);assert(plan.some(d=>d.slots.length));for(const slot of plan.flatMap(d=>d.slots)){assert(!byId[slot.exId].loadedAreas?.includes('knee'));assert.equal(slot.sets,1);assert(slot.rest>=120);for(const e of alternatives(slot.exId,q))assert(!e.loadedAreas?.includes('knee'))}}});
check('Recovered area restores selection; acute symptoms preserve explanatory day shells',()=>{const knee={area:'knee' as const,status:'recovered' as const,reportedAt:'',reviewed:false,history:[]};assert(makePlan({...p,injuries:[knee]}).flatMap(d=>d.slots).some(s=>byId[s.exId].loadedAreas?.includes('knee')));const urgent=makePlan({...p,urgentSymptoms:true});assert(urgent.length);assert(urgent.every(d=>d.slots.length===0&&d.warning))});
check('Goal cardio, mobility blocks and duration caps; ordinary beginner min2 sets',()=>{for(const g of Object.keys(goals)){for(const minutes of [30,45,60]){const plan=makePlan({...p,goal:g as any,minutes});assert(plan.every(d=>d.minutes<=minutes));assert(plan.flatMap(d=>d.slots).every(s=>s.sets>=2));if(['loss','fitness','endurance'].includes(g))assert(plan.some(d=>d.blocks.some(b=>b.kind==='cardio')));if(g==='mobility')assert(plan.some(d=>d.blocks.some(b=>b.kind==='mobility')))}}});
check('Preferred/disliked/exact gym selection and core rotation',()=>{const id='Machine_Bench_Press';const q={...p,preferredExerciseIds:[id]};assert(makePlan(q)[0].slots.some(s=>s.exId===id));assert(!makePlan({...q,dislikedExerciseIds:[id]}).flatMap(d=>d.slots).some(s=>s.exId===id));const ids=makePlan(p).flatMap(d=>d.slots).filter(s=>byId[s.exId].group==='core').map(s=>s.exId);assert.equal(new Set(ids).size,ids.length);const gym={id:'g',name:'One machine',equipment:['machine'] as any,exerciseIds:[id],exact:true,bars:[20],plates:[{kg:5,pairs:2}]};const slots=makePlan({...p,gyms:[gym],activeGymId:'g'}).flatMap(d=>d.slots);assert(slots.every(s=>byId[s.exId].eq==='body'||s.exId===id))});
const coverage:any[]=[];const eqs=Object.keys(equipment);for(let mask=1;mask<1<<eqs.length;mask++){const available=eqs.filter((_,i)=>mask>>i&1);const q={...p,equipment:available as any};for(const slot of makePlan(q).flatMap(d=>d.slots))if(!alternatives(slot.exId,q).length)coverage.push({equipment:available,id:slot.exId})}results.push({name:'Alternative coverage across all 255 equipment category combinations',status:coverage.length?'partial':'passed',slotsWithoutAlternative:coverage.length,explanation:'Unsupported combinations use explicit no-alternative/move-to-end state; never invent a movement equivalent.'});
check('Nutrition unspecified-sex fallback and correct percentage/macro arithmetic',()=>{for(const sex of ['male','female','unspecified']as const){for(const goal of ['loss','weight','strength']as const){const n=nutrition({...p,sex,goal})!;assert(n);assert(Math.abs(n.protein*4+n.carbs*4+n.fat*9-n.target)<8);assert.equal(n.multiplier,goal==='loss'?.85:goal==='weight'?1.1:1)}}assert.equal(nutrition({...p,health:'medical'}),null);assert.equal(nutrition({...p,weight:35,goal:'loss'}),null)});
check('Meal vegetarian/allergen filtering, accurate displayed totals and unresolved allergy block',()=>{const meal=mealPlan({...p,diet:'vegetarian',allergenTags:['milk','eggs'],allergies:'',foodReview:false})!;assert(meal);assert(meal.items.every(x=>x.veg&&!x.allergens.some(a=>['milk','eggs'].includes(a))));assert(Math.abs(meal.calories-(meal.protein*4+meal.carbs*4+meal.fat*9))<.01);assert.equal(mealPlan({...p,allergies:'unrecognized allergy',foodReview:false}),null)});
function session(i:number,weight=20,reps=12){const slots=makePlan(p)[0].slots;return sessionSchema.parse({id:'s'+i,date:`2026-09-${String(10+i*2).padStart(2,'0')}`,weekday:0,startedAt:'2026-09-10T12:00:00Z',finishedAt:'2026-09-10T13:00:00Z',title:'QA',titleEn:'QA',targetMinutes:45,slots,sets:Array.from({length:slots[0].sets},(_,n)=>({id:`s${i}-${n}`,slotKey:slots[0].key,exId:slots[0].exId,weight,reps,rir:3,at:'2026-09-10T12:00:00Z'})),skipped:[],notes:'',effort:5,extras:[],swaps:[],goalSnapshot:'muscle'})}
const b={...a.profiles[0],sessions:[0,1,2,3].map(i=>session(i))};
check('4-session progression, plateau and PR accuracy',()=>{const id=b.sessions[0].slots[0].exId;const adv=loadAdvice(id,b);assert(adv.increase);assert(adv.next!>20&&adv.next!<=21);assert(adv.plateau);const record={...b.sessions[0].sets[0],weight:22};assert(prTypes(record,b.sessions.flatMap(s=>s.sets)).includes('weight'));assert(!prTypes(b.sessions[0].sets[0],b.sessions.flatMap(s=>s.sets)).includes('weight'))});
check('Plate arithmetic both directions, finite quantities, round-down',()=>{assert.equal(plateTotal(20,[{kg:10,pairs:2},{kg:5,pairs:1}]),70);const s=plateSolve(72,20,[{kg:10,pairs:2},{kg:5,pairs:1}]);assert.equal(s.total,70);assert.equal(s.exact,false);assert.equal(plateSolve(70,20,[{kg:10,pairs:2},{kg:5,pairs:1}]).exact,true);assert.equal(plateSolve(15,20,[]).total,20)});
check('Comeback after missed scheduled session; no fabricated historic adherence',()=>{assert(comebackDue(b,new Date('2026-09-29T12:00:00')));const weeks=adherence({...b,profile:{...p,planHistory:[]}},new Date('2026-09-29'));assert(weeks.every(w=>w.planned===0&&w.percent===null))});
check('Physio candidate map exists and remains disabled without actual review',()=>{assert(Object.values(injuryCardioMap).every(v=>v.reviewed===false));assert(fs.readFileSync('lib/fitness.ts','utf8').includes('MUST be reviewed by a qualified physiotherapist before release'))});
check('Batch1 optional rest state preserves old envelopes, identities and historical zero RIR',()=>{
 const historical=JSON.parse(JSON.stringify({profiles:[b],activeId:p.id,schemaVersion:2}));
 historical.profiles[0].sessions[0].sets[0].rir=0;
 historical.profiles[0].sessions[0].sets[0].exId='unknown-historical-exercise';
 const raw=JSON.stringify(historical),loaded=migrate(historical);
 assert.equal(JSON.stringify(historical),raw);assert.deepEqual(loaded,historical);
 assert.equal(loaded.profiles[0].sessions[0].sets[0].id,b.sessions[0].sets[0].id);
 for(const deadline of [Date.now()+120000,null]){
  const next=JSON.parse(raw);next.profiles[0].sessions[0].restState={deadline,totalSeconds:120};
  assert.deepEqual(migrate(next),next);assert.deepEqual(migrate(migrate(next)),next);
 }
 const future={...historical,schemaVersion:3};assert.throws(()=>migrate(future),/FUTURE/);
 const invalid=JSON.parse(raw);invalid.profiles[0].sessions[0].restState={deadline:'bad',totalSeconds:120};assert.throws(()=>migrate(invalid));
});
const store=new Map<string,string>();(globalThis as any).localStorage={getItem:(k:string)=>store.get(k)??null,setItem:(k:string,v:string)=>store.set(k,v)};
async function storage(){store.set(KEY,JSON.stringify({data:{profiles:[{profile:oldProfile,sessions:[],reports:[]}],activeId:'qa'},revision:5}));const loaded=await(await localState('/api/state')).json() as any;assert(loaded.data.schemaVersion===2);assert(store.has(KEY+'-pre-v2'));const result=await localState('/api/state',{method:'PUT',body:JSON.stringify({data:loaded.data,revision:5})});assert(result.ok);assert(!(await localState('/api/state',{method:'PUT',body:JSON.stringify({data:loaded.data,revision:5})})).ok);results.push({name:'Same localStorage key, pre-migration backup, persistence and revision409',status:'passed'});const backup=store.get(KEY+'-pre-v2');
const saved=store.get(KEY)!;store.set(KEY,'not json');await assert.rejects(()=>localState('/api/state'));assert.equal(store.get(KEY),'not json');
const future=JSON.stringify({data:{...a,schemaVersion:3},revision:9});store.set(KEY,future);await assert.rejects(()=>localState('/api/state'));assert.equal(store.get(KEY),future);
store.set(KEY,JSON.stringify({data:{profiles:[{profile:oldProfile,sessions:[],reports:[]}],activeId:'qa'},revision:9}));await localState('/api/state');assert.equal(store.get(KEY+'-pre-v2'),backup);
store.set(KEY,saved);const before=store.get(KEY);const bad=JSON.parse(saved);bad.data.profiles[0].sessions=[{...b.sessions[0],restState:{deadline:-1,totalSeconds:120}}];await assert.rejects(()=>localState('/api/state',{method:'PUT',body:JSON.stringify(bad)}));assert.equal(store.get(KEY),before);assert.equal(store.get(KEY+'-pre-v2'),backup);
results.push({name:'Batch1 corruption/future-version protection, rejected writes and original migration backup preserved',status:'passed'});
fs.writeFileSync('tests/results.json',JSON.stringify({results,coverage},null,2));fs.writeFileSync('tests/fixture.json',JSON.stringify({data:{...a,profiles:[b]},revision:0}));console.log('PASS storage migration and409; coverage gaps',coverage.length)}void storage();
