const fs=require('node:fs'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require(process.env.OZ_JSDOM||'jsdom');
const path=require('node:path');const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(process.env.OZ_HTML||root+'/dist/Oz-Fit-v2.html','utf8');const fixture=JSON.parse(fs.readFileSync(__dirname+'/fixture.json','utf8'));
const wait=()=>new Promise(r=>setTimeout(r,80));
const results=[];
async function boot(data,setup){const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!e.message.includes('navigation')&&!e.message.includes('Could not parse CSS stylesheet'))errors.push(e.message)});vc.on('error',e=>errors.push(String(e)));
 const d=new JSDOM(html,{url:'https://oz-fit.invalid/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){if(data)w.localStorage.setItem('oz-fit-html-state-v1',JSON.stringify(data));w.matchMedia=()=>({matches:false,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){}});w.ResizeObserver=class{observe(){}disconnect(){}};w.PointerEvent=w.MouseEvent;w.HTMLElement.prototype.scrollIntoView=function(){};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.HTMLElement.prototype.hasPointerCapture=()=>false;w.HTMLElement.prototype.releasePointerCapture=()=>{};w.HTMLElement.prototype.setPointerCapture=()=>{};setup?.(w);}});await wait();await wait();return{d,w:d.window,doc:d.window.document,errors}}
function button(doc,text){const b=[...doc.querySelectorAll('button')].find(x=>x.textContent.trim()===text);assert(b,'Missing button '+text);return b}
function click(w,b){b.dispatchEvent(new w.MouseEvent('click',{bubbles:true,cancelable:true}))}
function tab(w,doc,text){const b=button(doc,text);b.dispatchEvent(new w.MouseEvent('mousedown',{bubbles:true,button:0}));click(w,b)}
function input(w,el,value){Object.getOwnPropertyDescriptor(w.HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new w.Event('input',{bubbles:true}));el.dispatchEvent(new w.Event('change',{bubbles:true}))}
function check(name,fn){fn();results.push({name,status:'passed'});console.log('PASS',name)}
(async()=>{
 let x=await boot();check('Onboarding Arabic renders with labelled controls',()=>{assert.equal(x.doc.documentElement.dir,'rtl');assert(x.doc.querySelector('h1'));for(const el of x.doc.querySelectorAll('input:not([type=hidden])'))assert(el.labels?.length||el.getAttribute('aria-label'),'Unlabelled input')});
 click(x.w,button(x.doc,'English'));await wait();check('English switches document direction and onboarding strings',()=>{assert.equal(x.doc.documentElement.dir,'ltr');assert(x.doc.body.textContent.includes('Next'))});x.d.window.close();
 x=await boot(fixture);const {w,doc}=x;tab(w,doc,'تقدمي');await wait();check('Four-session Progress renders charts, volume and suggestions',()=>{assert(doc.querySelectorAll('figure.chart svg').length>=1);assert(doc.body.textContent.includes('حجم الأسبوع'));assert(doc.body.textContent.includes('اقتراح')||doc.body.textContent.includes('ثبّت الحمل'))});
 tab(w,doc,'خطتي');await wait();check('Nutrition renders computed Egyptian meal example',()=>{assert(doc.querySelector('.nutrition-number'));assert(doc.body.textContent.includes('بروتين'))});
 tab(w,doc,'اليوم');await wait();click(w,doc.querySelectorAll('.week-day')[fixture.data.profiles[0].profile.days[0]===0?1:0]);await wait();const training=[...doc.querySelectorAll('.week-day')].find(b=>b.textContent.includes('تمرين'));click(w,training);await wait();click(w,button(doc,'ابدأ الحصة'));await wait();
 check('Start opens set dialog with accessible labels',()=>{assert(doc.querySelector('[role=dialog]'));assert(doc.querySelector('.logging-controls'));});
 const weight=doc.querySelector('.logging-controls input');input(w,weight,'20');await wait();click(w,button(doc,'سجل المجموعة وابدأ الراحة'));await wait();
 check('One tap stores first set and starts timer',()=>{const s=JSON.parse(w.localStorage.getItem('oz-fit-html-state-v1')).data.profiles[0].sessions.at(-1);assert.equal(s.sets.length,1);assert.equal(s.sets[0].weight,20);assert(doc.querySelector('[role=timer]'));});
 click(w,button(doc,'سجل المجموعة وابدأ الراحة'));await wait();check('Second set repeats retained weight and reps with one tap',()=>{const s=JSON.parse(w.localStorage.getItem('oz-fit-html-state-v1')).data.profiles[0].sessions.at(-1);assert.equal(s.sets.length,2);assert.equal(s.sets[0].weight,s.sets[1].weight);assert.equal(s.sets[0].reps,s.sets[1].reps)});
 click(w,button(doc,'التمرين التالي'));await wait();const current=JSON.parse(w.localStorage.getItem('oz-fit-html-state-v1')).data.profiles[0].sessions.at(-1).slots[1].exId;
 const busyButton=[...doc.querySelectorAll('[role=dialog] button')].find(b=>b.textContent.trim()==='الجهاز مشغول');click(w,busyButton);await wait();
 check('Machine busy records same-pattern swap and keeps logged sets',()=>{const s=JSON.parse(w.localStorage.getItem('oz-fit-html-state-v1')).data.profiles[0].sessions.at(-1);assert.equal(s.swaps.at(-1).reason,'machine_busy');assert.equal(s.swaps.at(-1).from,current);assert.equal(s.sets.length,2)});
 click(w,button(doc,'ارجع للأصل'));await wait();check('Swap back restores original without erasing prior sets',()=>{const s=JSON.parse(w.localStorage.getItem('oz-fit-html-state-v1')).data.profiles[0].sessions.at(-1);assert.equal(s.slots[1].exId,current);assert.equal(s.sets.length,2)});
 check('No React/runtime console errors in tested flow',()=>assert.deepEqual(x.errors,[]));x.d.window.close();
 const injured=JSON.parse(JSON.stringify(fixture));injured.data.profiles[0].profile.health='injury';injured.data.profiles[0].profile.injuries=[{area:'knee',reportedAt:'2026-09-29',status:'active',reviewed:false,history:[]}];injured.data.profiles[0].profile.prescribedRehab=[{id:'prescribed-test',name:'Therapist test prescription',sets:1,reps:5,hold:0,frequency:'Per clinician',notes:'Synthetic',placement:'separate',days:[new Date().getDay()]}];x=await boot(injured);check('Active knee shows visible review banner and nonblank Today',()=>{assert(x.doc.querySelector('.safety-banner'));assert(x.doc.querySelector('.week-strip'));assert(x.doc.body.textContent.includes('وصفة مختصك'))});const cb=x.doc.querySelector('.rehab-item [role=checkbox]');click(x.w,cb);await wait();check('Separate-day prescribed rehab logs without a workout',()=>{const b=JSON.parse(x.w.localStorage.getItem('oz-fit-html-state-v1')).data.profiles[0];assert.equal(b.rehabLogs.length,1);assert.equal(b.rehabLogs[0].prescription.reps,5);assert.equal(b.sessions.length,4)});x.d.window.close();await require('./batch1-dom.cjs')({boot,wait,button,click,tab,input,check,fixture});await require('./batch2-dom.cjs')({boot,wait,button,click,tab,input,check,fixture});fs.writeFileSync(__dirname+'/dom-results.json',JSON.stringify({environment:'jsdom DOM-only; no layout, visual, device, audio or install verification. jsdom cannot parse all Tailwind CSS; its stylesheet parser warning is excluded from runtime error check.',results},null,2));
})().catch(e=>{console.error(e);process.exit(1)});
