import React,{useState,useEffect,useRef} from 'react';
import {Dumbbell,Flame,Activity,Target,Upload,Check} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';import {Progress} from '@/components/ui/progress';
import {Profile,Lang,goals,days,equipment,areas,recommended,reason,profileSchema,ageAt,splits,words,chooseDays,localDate,transitionInjury,Area} from '@/lib/fitness';import Body from './body';import {asset} from '../asset';
export function hasUnsupportedPriority(error:unknown){return Array.isArray((error as any)?.issues)&&(error as any).issues.some((issue:any)=>issue.path?.at(-1)==='priority')}
export const profileSections=[
 {id:'goals',labels:['الأهداف','Goals']},
 {id:'basics',labels:['البيانات الشخصية والخبرة','Personal details & experience']},
 {id:'availability',labels:['الإتاحة ومدة الحصة','Availability & duration']},
 {id:'equipment',labels:['المعدات العامة وأولوية العضلات','General equipment & muscle priority']},
 {id:'health',labels:['الصحة والروتين اليومي','Health & daily routine']}
] as const;
export type ProfileSection=typeof profileSections[number]['id'];
export function Choices({value,onChange,options,label}:{value:string;onChange:(s:any)=>void;options:[string,string,string?][];label?:string}){return <RadioGroup aria-label={label} value={value} onValueChange={onChange} className="choices">{options.map(([id,text,desc])=><label className={'option '+(value===id?'selected':'')} key={id}><RadioGroupItem value={id}/><span><strong>{text}</strong>{desc&&<small>{desc}</small>}</span></label>)}</RadioGroup>}
export function InjuryEditor({p,put,lang}:{p:any;put:(k:string,v:any)=>void;lang:Lang}){const t=(a:string,e:string)=>words(lang,a,e);return <section><h3>{t('المناطق المتأثرة','Affected areas')}</h3><div className="chips">{Object.entries(areas).map(([k,v])=>{const has=p.injuries?.some((i:any)=>i.area===k&&i.status!=='recovered');return <button type="button" className={'chip '+(has?'active':'')} aria-pressed={!!has} key={k} onClick={()=>{if(has&&!window.confirm(t('تسجل المنطقة كمتعافية حسب إفادتك؟ سجل الإصابة هيفضل محفوظ.','Mark this area recovered, as reported by you? Its injury history will be kept.')))return;put('injuries',transitionInjury(p.injuries??[],k as Area,has?'recovered':'active'))}}>{v[lang==='ar'?0:1]}</button>})}</div>{p.injuries?.map((i:any)=><div className="injury-row" key={i.area}><strong>{areas[i.area as keyof typeof areas][lang==='ar'?0:1]}</strong><label>{t('الحالة المبلّغ عنها','Reported status')}<select value={i.status} onChange={e=>put('injuries',transitionInjury(p.injuries,i.area,e.target.value as 'active'|'improving'|'recovered'))}><option value="active">{t('نشطة — استبعاد التحميل','Active — exclude loading')}</option><option value="improving">{t('بتتحسن — رجوع مقيد','Improving — restricted return')}</option><option value="recovered">{t('تم التعافي حسب إفادتك','Recovered, self-reported')}</option></select></label>{i.status!=='recovered'&&<button type="button" className="secondary" onClick={()=>put('injuries',transitionInjury(p.injuries,i.area,'recovered'))}>{t('تم التعافي','Mark recovered')}</button>}{i.status==='improving'&&<label className="option"><Checkbox checked={i.reviewed} onCheckedChange={v=>put('injuries',p.injuries.map((x:any)=>x.area===i.area?{...x,reviewed:!!v}:x))}/>{t('مختص راجع الرجوع للتحميل الخفيف؛ هلتزم بقيوده','A professional reviewed light loading; I will follow their restrictions')}</label>}</div>)}<p className="muted">{t('اختيار «تم التعافي» إفادة منك، مش تشخيص. ارجع تدريجيًا والتزم بأي قيود باقية. التأهيل مش بيتخمن.','Recovered is self-reported, not a diagnosis. Return gradually and follow remaining restrictions. Rehabilitation is not guessed.')}</p></section>}
export default function Onboarding({lang,initial,section,busy,saveError,onSave,onCancel}:{lang:Lang;initial?:Profile;section?:ProfileSection;busy:boolean;saveError?:string;onSave:(p:Profile)=>Promise<boolean>;onCancel?:()=>void}){const t=(a:string,e:string)=>words(lang,a,e);const li=lang==='ar'?0:1;const [step,setStep]=useState(section?profileSections.findIndex(s=>s.id===section):0),[err,setErr]=useState('');const heading=useRef<HTMLHeadingElement>(null),feedback=useRef<HTMLParagraphElement>(null);const [p,setP]=useState<any>(initial??{name:'',age:'',birthDate:'',weight:'',height:'',measuredAt:localDate(),goal:'',secondaryGoals:[],experience:'',days:[],availableDays:[],sessionsPerWeek:3,weekStartsOn:lang==='ar'?6:1,minutes:45,dayMinutes:{},equipment:[],priority:'balanced',health:'',restrictions:'',injuries:[],urgentSymptoms:false,sex:'unspecified',activity:'low',sleep:7,diet:'mixed',allergies:'',split:'upper',stage:0,rehab:'',nutritionEnabled:false});const put=(k:string,v:any)=>{setErr('');setP((p:any)=>({...p,[k]:v}))};useEffect(()=>{heading.current?.focus()},[step]);useEffect(()=>{if(err||saveError)feedback.current?.focus()},[err,saveError]);
const titles=[t('اختار هدفك الأساسي','Choose your primary goal'),t('نبدأ ببياناتك','Your starting point'),t('أيامك… على وقتك','Your week, your time'),t('معدات الجيم','Your gym equipment'),t('نراعي جسمك','Your health and routine'),t('راجع خطتك','Review your plan')];
const priorityError=profileSchema.shape.priority.safeParse(p.priority).success?'':t('اختار توازن الجسم أو إحدى العضلات المعروضة. المرونة متاحة ضمن الأهداف.','Choose Balanced or one of the listed muscle groups. Mobility is available under goals.');
function validation(step:number){if(step===0&&!p.goal)return t('اختار هدف أساسي، وبعده أهداف مساندة لو حابب.','Choose a primary goal; supporting goals are optional.');const age=p.birthDate?ageAt(p.birthDate):+p.age;if(step===1&&age>0&&age<18)return t('Oz Fit الحالي مخصص للبالغين 18 سنة فأكثر. نحتاج نسخة بإشراف ولي الأمر ومدرب مؤهل للأصغر سنًا؛ مش هنعمل خطة بالغين ليك.','This Oz Fit version is for adults 18+. Younger users need a guardian and appropriately qualified coach; an adult plan will not be generated.');if(step===1&&(!p.name.trim()||!p.experience||age<18||age>90||p.weight<30||p.weight>300||p.height<120||p.height>230))return t('راجع الاسم والعمر والخبرة، الوزن 30–300 والطول 120–230.','Check name, age and experience; weight 30–300 kg, height 120–230 cm.');if(step===2&&(p.availableDays.length<p.sessionsPerWeek||p.sessionsPerWeek<2))return t('الأيام المتاحة لازم تكفي عدد الحصص المختار.','Available days must cover your chosen session count.');if(step===3&&!p.equipment.length)return t('اختار المعدات الموجودة فعلًا.','Choose the equipment you have.');if(step===4&&!p.health)return t('حدد الحالة الصحية أو اختار مش متأكد.','Choose a health status or Unsure.');return ''}
function next(){if(step===3&&priorityError)return;const message=validation(step);setErr(message);if(!message)setStep(step+1)}
async function intake(file:File){try{if(file.size>500000)throw Error();const text=await file.text(),m=text.match(/```json\s*([\s\S]*?)```/),d=JSON.parse(m?m[1]:text);if(d.schemaVersion!=='fitness-profile-draft/1')throw Error();const ws=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];const map:any={fat_loss:'loss',muscle_gain:'muscle',weight_gain:'weight',strength:'strength',aerobic_fitness:'fitness',muscular_endurance:'endurance',general_fitness:'fitness',mobility:'mobility'};const weight=d.measurements?.filter((x:any)=>x.type==='weight'&&x.unit==='kg').at(-1);setP((v:any)=>({...v,name:d.subjectLabel??v.name,birthDate:d.demographics?.birthDate??'',age:d.demographics?.ageYears??v.age,height:d.demographics?.heightCm??v.height,weight:weight?.value??v.weight,goal:map[d.goals?.primary]??v.goal,availableDays:(d.training?.availableDays??[]).map((x:any)=>ws.indexOf(x.weekday)).filter((x:number)=>x>=0),health:'unknown',restrictions:JSON.stringify(d.health??{}).slice(0,2000)}));setErr(t('دي مسودة. راجع كل البيانات وحدد الأجهزة والقيود بنفسك.','Draft imported. Review every field and confirm equipment and restrictions.'))}catch{setErr(t('ملف غير صالح. استخدم برومبت البيانات المرفق.','Invalid file. Use the included intake prompt.'))}}
async function finish(){
 setErr('');if(priorityError){setStep(3);return}const message=section?validation(step):[0,1,2,3,4].map(validation).find(Boolean);if(message){setErr(message);return}
 try{
  const c={...p,id:initial?.id??crypto.randomUUID(),createdAt:initial?.createdAt??new Date().toISOString()};
  if(!section||section==='basics'){c.age=p.birthDate?ageAt(p.birthDate):+p.age;c.weight=+p.weight;c.height=+p.height}
  if(!section||section==='goals')c.secondaryGoals=p.secondaryGoals.filter((g:string)=>g!==p.goal);
  if(!section||section==='availability'){
   // Keep a user's valid custom distribution; unrelated edits never reschedule.
   const d=initial&&initial.days.length===+p.sessionsPerWeek&&initial.days.every(day=>p.availableDays.includes(day))?[...initial.days]:chooseDays(p.availableDays,+p.sessionsPerWeek,+p.weekStartsOn);
   c.days=d;const changed=!initial||d.length!==initial.days.length||d.some(day=>!initial.days.includes(day));
   c.planHistory=changed?[...(initial?.planHistory??[]),{effectiveFrom:localDate(),days:d}]:initial.planHistory;
  }
  c.split=initial?.split??recommended(c);
  const saved=await onSave(profileSchema.parse(c));
  if(!saved)feedback.current?.focus();
 }catch{setErr(t('راجع الحقول والأيام؛ في قيمة ناقصة أو خارج الحدود.','Review fields and days; a value is missing or out of range.'))}
}
return <main className="onboarding" data-profile-section={section}>{!section&&<><div className="step-row"><span>{t('ملفك الرياضي','Your training profile')}</span><span>{step+1} / 6</span></div><Progress value={(step+1)/6*100} aria-label={t('تقدم الإعداد','Setup progress')}/></>}<div className="intro"><span className="eyebrow">OZ FIT</span><h1 id="profile-section-title" ref={heading} tabIndex={-1}>{section?profileSections[step].labels[li]:titles[step]}</h1>{section&&<p className="muted">{t('عدّل القسم ده واحفظه، أو الغِ للرجوع بدون تغييرات.','Edit this section and save, or cancel to return without changes.')}</p>}</div><fieldset disabled={busy} aria-labelledby="profile-section-title">
{step===0&&<><h2>{t('هدف أساسي واحد','One primary goal')}</h2><p className="muted">{t('اختار أهم نتيجة ليك. الهدف الأساسي يوجّه الخطة وتقدير السعرات.','Choose your main outcome. The primary goal guides your plan and calorie estimates.')}</p><Choices label={t('الهدف الأساسي','Primary goal')} value={p.goal} onChange={v=>{setErr('');setP((current:any)=>({...current,goal:v,secondaryGoals:current.secondaryGoals.filter((g:string)=>g!==v)}))}} options={Object.entries(goals).map(([k,v])=>[k,v[li]])}/>{p.goal&&<details className="supporting-goals"><summary>{t('أهداف مساندة — اختياري','Supporting goals — optional')} · {p.secondaryGoals.filter((g:string)=>g!==p.goal).length}</summary><p className="muted">{t('ممكن تختار أكتر من هدف إضافي، أو تسيبها فاضية. الهدف الأساسي يفضل له الأولوية.','Choose any additional goals, or leave these empty. Your primary goal keeps priority.')}</p><div className="chips" role="group" aria-label={t('الأهداف المساندة','Supporting goals')}>{Object.entries(goals).filter(([k])=>k!==p.goal).map(([k,v])=><button type="button" key={k} aria-pressed={p.secondaryGoals.includes(k)} className={'chip '+(p.secondaryGoals.includes(k)?'active':'')} onClick={()=>put('secondaryGoals',p.secondaryGoals.includes(k)?p.secondaryGoals.filter((x:string)=>x!==k):[...p.secondaryGoals,k])}>{v[li]}</button>)}</div></details>}{([p.goal,...p.secondaryGoals].includes('loss')&&[p.goal,...p.secondaryGoals].some((x:string)=>['muscle','weight'].includes(x)))&&<p className="note">{t('أهداف الوزن متعارضة؛ السعرات هتتبع الهدف الأساسي، والتدريب يحافظ على باقي الأولويات.','Weight goals conflict. Calories follow the primary goal; training supports other priorities.')}</p>}{!section&&<div className="import-inline"><label className="secondary file-label"><Upload/>{t('استيراد مسودة AI','Import AI draft')}<input type="file" accept=".json,.md,.txt" onChange={e=>e.target.files?.[0]&&intake(e.target.files[0])}/></label><a href={asset('/Fitness-V2-AI-Intake-Prompt.md')} download="Oz-Fit-Intake.md">{t('تحميل البرومبت','Download prompt')}</a></div>}</>}
{step===1&&<><div className="form-grid">{[['name',t('اسم الملف','Profile name'),'text'],['birthDate',t('تاريخ الميلاد — اختياري','Date of birth — optional'),'date'],['age',t('العمر','Age'),'number'],['weight',t('الوزن · كجم','Weight · kg'),'number'],['height',t('الطول · سم','Height · cm'),'number'],['measuredAt',t('تاريخ الوزن','Measurement date'),'date']].map(([k,label,type])=><div className="field" key={k}><label htmlFor={k}>{label}</label><input id={k} type={type} disabled={k==='age'&&!!p.birthDate} value={k==='age'&&p.birthDate?ageAt(p.birthDate):p[k]} onChange={e=>put(k,e.target.value)}/></div>)}</div><Choices label={t('الخبرة','Experience')} value={p.experience} onChange={v=>put('experience',v)} options={[["beginner",t('مبتدئ','Beginner')],["returning",t('راجع بعد انقطاع','Returning')],["regular",t('بتمرن بانتظام','Regular training')]]}/></>}
{step===2&&<><label>{t('كام حصة فعلًا في الأسبوع؟','How many training sessions per week?')}<select value={p.sessionsPerWeek} onChange={e=>put('sessionsPerWeek',+e.target.value)}>{[2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label><h3>{t('كل الأيام المتاحة — هنختار منها عدد الحصص فقط','All available days — we select only your session count')}</h3><div className="chips">{days.map((d,i)=><button className={'chip '+(p.availableDays.includes(i)?'active':'')} aria-pressed={p.availableDays.includes(i)} key={i} onClick={()=>put('availableDays',p.availableDays.includes(i)?p.availableDays.filter((x:number)=>x!==i):[...p.availableDays,i])}>{d[li]}</button>)}</div><label>{t('الأسبوع يبدأ','Week starts on')}<select value={p.weekStartsOn} onChange={e=>put('weekStartsOn',+e.target.value)}>{days.map((d,i)=><option value={i} key={i}>{d[li]}</option>)}</select></label><Choices label={t('مدة الحصة','Session duration')} value={String(p.minutes)} onChange={v=>put('minutes',+v)} options={[30,45,60,75,90].map(n=>[String(n),n+' '+t('دقيقة','minutes')])}/><details><summary>{t('وقت مختلف لكل يوم','Different time per day')}</summary>{p.availableDays.map((i:number)=><label key={i}>{days[i][li]}<input type="number" min={30} max={100} value={p.dayMinutes[String(i)]??p.minutes} onChange={e=>put('dayMinutes',{...p.dayMinutes,[String(i)]:+e.target.value})}/></label>)}</details></>}
{step===3&&<><div className="equip-grid">{Object.entries(equipment).map(([k,v])=><label className="option" key={k}><Checkbox checked={p.equipment.includes(k)} onCheckedChange={()=>put('equipment',p.equipment.includes(k)?p.equipment.filter((x:string)=>x!==k):[...p.equipment,k])}/>{v[li]}</label>)}</div><p>{section?t('دي المعدات العامة. لو اخترت جيم نشط، معداته هي المستخدمة؛ عدّلها من «جيمي».','These are general equipment settings. An active gym uses its own equipment; edit that in My gym.'):t('بعد الإعداد تقدر تحدد كل جهاز بصورته في «جيمي».','After setup, choose specific machines by photo in My gym.')}</p><div role="group" aria-label={t('أولوية العضلات','Muscle priority')} aria-invalid={!!priorityError} aria-describedby={priorityError?'priority-error':undefined}><Body selected={p.priority} onSelect={v=>put('priority',v)} lang={lang}/>{priorityError&&<p id="priority-error" className="field-error" role="alert">{priorityError}</p>}</div></>}
{step===4&&<><Choices label={t('الحالة الصحية','Health status')} value={p.health} onChange={v=>put('health',v)} options={[["none",t('لا قيود معروفة','No known restrictions')],["injury",t('إصابة أو ألم','Injury or pain')],["medical",t('حالة صحية أو دواء مؤثر','Medical condition or relevant medication')],["unknown",t('مش متأكد','Unsure')]]}/>{p.health&&p.health!=='none'&&<><InjuryEditor p={p} put={put} lang={lang}/><label>{t('ملاحظات وتعليمات مختص','Additional notes / clinician restrictions')}<textarea maxLength={2000} value={p.restrictions} onChange={e=>put('restrictions',e.target.value)}/></label><label className="option"><Checkbox checked={p.urgentSymptoms} onCheckedChange={v=>put('urgentSymptoms',!!v)}/>{t('عندي حاليًا ألم صدر مع المجهود، إغماء، ضعف/تنميل جديد متزايد أو منع من التمرين','Current exertional chest pain, fainting, new worsening weakness/numbness, or instructions not to exercise')}</label><p className="note">{t('راجع مع مختص قبل اتباع الخطة المحافظة. دي مش خطة علاج. الأعراض الحادة توقف اقتراح التمرين وتحتاج تقييمًا عاجلًا.','Review with a professional before following the conservative plan. It is not treatment. Acute symptoms need urgent assessment before exercise.')}</p></>}<Choices label={t('النشاط اليومي','Daily activity')} value={p.activity} onChange={v=>put('activity',v)} options={[["low",t('جلوس أغلب اليوم','Mostly seated')],["moderate",t('مشي وحركة','Walking and active')],["high",t('عمل بدني','Physical work')]]}/><label>{t('متوسط ساعات النوم','Average sleep hours')}<input type="number" min={0} max={16} value={p.sleep} onChange={e=>put('sleep',+e.target.value)}/></label></>}
{step===5&&<div className="panel"><span className="badge">{t('التقسيمة المقترحة','Recommended split')}</span><h2>{splits[recommended(p)][li]}</h2><p>{reason(p,lang)}</p><p>{t('أيام التمرين المختارة','Selected training days')}: {chooseDays(p.availableDays,p.sessionsPerWeek,p.weekStartsOn).map(d=>days[d][li]).join(' · ')}</p><p>{t('تقدر تغيّر توزيع الأيام من «خطتي»، داخل الأيام المتاحة. الوزن والطول مش اختبار قوة، هنراجع الحمل من أدائك الفعلي.','Change training days within your availability in My plan. Body size does not measure strength; loads are refined from performance.')}</p></div>}
</fieldset>{(err||saveError)&&<p ref={feedback} tabIndex={-1} className="error" role="alert">{err||saveError}</p>}<div className="nav-row"><button className="secondary" disabled={busy||(!section&&step===0&&!onCancel)} onClick={()=>section?onCancel?.():step?setStep(step-1):onCancel?.()}>{section?t('إلغاء','Cancel'):step?t('رجوع','Back'):t('إلغاء','Cancel')}</button><button className="primary" disabled={busy} onClick={section||step===5?finish:next}>{busy?t('جاري الحفظ','Saving'):section?t('حفظ التغييرات','Save changes'):step===5?t('احفظ وافتح خطتي','Save my plan'):t('التالي','Next')}</button></div></main>}
