import {z} from 'zod';
import {legacyExercises} from './legacy';
import {extraExercises} from './extra';
export type Lang='ar'|'en';export const words=(l:Lang,a:string,e:string)=>l==='ar'?a:e;
export const groups={chest:['صدر','Chest'],back:['ضهر','Back'],legs:['رجل','Legs'],shoulders:['كتف','Shoulders'],arms:['دراع','Arms'],core:['بطن','Core'],cardio:['لياقة','Cardio'],mobility:['مرونة','Mobility']} as const;export type Group=keyof typeof groups;
export const days=[['الأحد','Sunday'],['الاثنين','Monday'],['الثلاثاء','Tuesday'],['الأربعاء','Wednesday'],['الخميس','Thursday'],['الجمعة','Friday'],['السبت','Saturday']];
export const goals={muscle:['بناء عضلات','Build muscle'],weight:['زيادة وزن','Gain weight'],loss:['خسارة دهون','Fat loss'],strength:['زيادة قوة','Strength'],endurance:['تحمل عضلي','Endurance'],fitness:['لياقة عامة','Fitness'],mobility:['مرونة وحركة','Mobility']};
export const equipment={machine:['أجهزة المقاومة','Machines'],cable:['الكابلات','Cables'],dumbbell:['الدمبل والبنش','Dumbbells & bench'],barbell:['بار وراك','Barbell & rack'],cardio:['أجهزة اللياقة','Cardio'],body:['وزن الجسم / مات','Bodyweight / mat'],kettlebell:['كيتل بيل','Kettlebell'],band:['مطاط + بار عقلة','Band + pull-up bar']};
export const splits={upper:['علوي / سفلي','Upper / Lower'],ppl:['دفع / سحب / رجل','Push / Pull / Legs'],bro:['تقسيم عضلات','Bro split'],full:['جسم كامل','Full body'],arnold:['أرنولد','Arnold split']};
export const areas={shoulder:['كتف','Shoulder'],elbow:['كوع / رسغ','Elbow / wrist'],back:['أسفل الضهر','Lower back'],hip:['حوض','Hip'],knee:['ركبة','Knee'],ankle:['كاحل','Ankle'],neck:['رقبة','Neck']};export type Area=keyof typeof areas;
const f=z.number().finite();const ids=z.array(z.string().max(100)).max(150).default([]);const weekday=f.int().min(0).max(6);const goal=z.enum(['muscle','weight','loss','strength','endurance','fitness','mobility']);const eq=z.enum(['machine','cable','dumbbell','barbell','cardio','body','kettlebell','band']);
export const injurySchema=z.object({area:z.enum(['shoulder','elbow','back','hip','knee','ankle','neck']),reportedAt:z.string().default(''),status:z.enum(['active','improving','recovered']).default('active'),reviewed:z.boolean().default(false),history:z.array(z.object({status:z.string(),at:z.string()})).default([])});
export const rehabSchema=z.object({id:z.string(),name:z.string().min(1).max(100),sets:f.int().min(1).max(20),reps:f.int().min(0).max(100),hold:f.min(0).max(600),frequency:z.string().max(100),notes:z.string().max(1000),placement:z.enum(['before','after','separate']),days:z.array(weekday).default([])});
export const gymSchema=z.object({id:z.string(),name:z.string().min(1).max(80),equipment:z.array(eq).min(1),exerciseIds:ids,exact:z.boolean().default(false),bars:z.array(f.min(0).max(100)).default([20]),plates:z.array(z.object({kg:f.positive().max(100),pairs:f.int().min(1).max(30)})).default([{kg:1.25,pairs:2},{kg:2.5,pairs:2},{kg:5,pairs:2},{kg:10,pairs:2},{kg:20,pairs:2}])});
export const profileSchema=z.object({id:z.string().max(80),name:z.string().trim().min(1).max(60),age:f.int().min(18).max(90),birthDate:z.string().max(10).default(''),weight:f.min(30).max(300),height:f.min(120).max(230),measuredAt:z.string().max(10),goal,secondaryGoals:z.array(goal).max(6).default([]),experience:z.enum(['beginner','returning','regular']),days:z.array(weekday).min(2).max(6),availableDays:z.array(weekday).min(2).max(7).default([0,2,4]),sessionsPerWeek:f.int().min(2).max(6).default(3),weekStartsOn:weekday.default(6),minutes:f.int().min(30).max(100),dayMinutes:z.record(z.string(),f.int().min(30).max(100)).default({}),equipment:z.array(eq).min(1),priority:z.enum(['balanced','chest','back','legs','shoulders','arms','core']),health:z.enum(['none','injury','medical','unknown']),restrictions:z.string().max(2000),urgentSymptoms:z.boolean().default(false),injuries:z.array(injurySchema).max(7).default([]),sex:z.enum(['male','female','unspecified']),activity:z.enum(['low','moderate','high']),sleep:f.min(0).max(16),diet:z.enum(['mixed','vegetarian']),allergies:z.string().max(500),allergenTags:z.array(z.string()).default([]),foodReview:z.boolean().default(false),split:z.enum(['upper','ppl','bro','full','arnold']),stage:f.int().min(0).max(2),createdAt:z.string().max(40),rehab:z.string().max(3000).default(''),prescribedRehab:z.array(rehabSchema).max(30).default([]),nutritionEnabled:z.boolean().default(false),preferredExerciseIds:ids,dislikedExerciseIds:ids,gyms:z.array(gymSchema).max(10).default([]),activeGymId:z.string().default(''),upperIncrement:f.positive().max(10).default(1),lowerIncrement:f.positive().max(20).default(2.5),remindersEnabled:z.boolean().default(false),reminderTime:z.string().default('18:00'),lastBackupSessionCount:f.int().min(0).default(0),shareNameEnabled:z.boolean().default(false),comebackDismissed:z.string().default(''),planHistory:z.array(z.object({effectiveFrom:z.string(),days:z.array(weekday)})).default([])});
export type Profile=z.infer<typeof profileSchema>;
export type Exercise={id:string;ar:string;en:string;group:Group;pattern:string;eq:string;reps:[number,number];rest:number;arCue:string;enCue:string;unit:'each'|'stack'|'total'|'body';compound:boolean;loadedAreas?:Area[];aliases?:string[];mode?:'reps'|'seconds'|'minutes';assisted?:boolean};
const patternLoads:Record<string,Area[]>={push:['shoulder','elbow','neck'],incline:['shoulder','elbow','neck'],decline:['shoulder','elbow','neck'],fly:['shoulder','elbow'],row:['shoulder','elbow','back','neck'],vertical:['shoulder','elbow','neck'],knee:['knee','hip','ankle','back'],curl:['knee','hip'],extension:['knee'],hip:['hip','back','knee'],hinge:['hip','back','knee','neck'],calf:['ankle','knee'],adductor:['hip'],abductor:['hip'],press:['shoulder','elbow','back','neck'],lateral:['shoulder','neck'],rear:['shoulder','neck','elbow'],triceps:['elbow','shoulder'],biceps:['elbow','shoulder'],core:['back','hip','neck'],front:['shoulder','neck'],pullover:['shoulder','elbow','back','neck']};
export const exercises:Exercise[]=[...legacyExercises,...extraExercises].map(e=>({...e,loadedAreas:e.loadedAreas??patternLoads[e.pattern]??Object.keys(areas) as Area[],aliases:[e.ar,e.en,...(e.aliases??[])],mode:e.mode??'reps'}));export const byId=Object.fromEntries(exercises.map(e=>[e.id,e]));
export type Slot={key:string;exId:string;sets:number;low:number;high:number;rest:number};
const slotSchema=z.object({key:z.string().max(80),exId:z.string().max(100),sets:f.int().min(1).max(6),low:f.min(1).max(120),high:f.min(1).max(120),rest:f.min(0).max(600)});
export const setSchema=z.object({id:z.string().max(80),slotKey:z.string().max(80),exId:z.string().max(100),weight:f.min(0).max(1500),reps:f.int().min(1).max(120),rir:f.int().min(0).max(10),at:z.string().max(40),gymId:z.string().default('')});
export const restStateSchema=z.object({deadline:f.min(0).nullable(),totalSeconds:f.min(0).max(600)});
export const sessionSchema=z.object({restState:restStateSchema.optional(),id:z.string().max(80),date:z.string().max(10),weekday,startedAt:z.string().max(40),finishedAt:z.string().max(40).nullable(),title:z.string().max(100),titleEn:z.string().max(100),targetMinutes:f.min(1).max(240),slots:z.array(slotSchema).max(30),sets:z.array(setSchema).max(250),skipped:z.array(z.string().max(80)).max(30),notes:z.string().max(2000),effort:f.min(0).max(10),extras:z.array(z.object({kind:z.string().max(100),minutes:f.min(0).max(120)})).max(50),swaps:z.array(z.object({slot:z.string(),from:z.string(),to:z.string(),reason:z.string(),at:z.string()})).max(100),gymId:z.string().default(''),goalSnapshot:z.string().default(''),painByArea:z.record(z.string(),f.min(0).max(10)).default({}),rehabDone:z.array(z.string()).default([]),comeback:z.boolean().default(false),blocks:z.array(z.object({id:z.string(),kind:z.string(),minutes:f,exId:z.string(),optional:z.boolean().default(false)})).default([])});
export type Session=z.infer<typeof sessionSchema>;export type LoggedSet=z.infer<typeof setSchema>;
export const reportSchema=z.object({id:z.string().max(80),fileKey:z.string().max(180),date:z.string().max(10),weight:f.min(0).max(300).nullable(),fat:f.min(0).max(70).nullable(),muscle:f.min(0).max(150).nullable(),bmr:f.min(0).max(5000).nullable(),confirmed:z.boolean(),raw:z.string().max(10000)});
export const bundleSchema=z.object({profile:profileSchema,sessions:z.array(sessionSchema).max(1000),reports:z.array(reportSchema).max(200),rehabLogs:z.array(z.object({id:z.string(),date:z.string(),at:z.string(),prescription:rehabSchema})).max(3000).default([])});export type Bundle=z.infer<typeof bundleSchema>;
export const accountSchema=z.object({profiles:z.array(bundleSchema).max(20),activeId:z.string().max(80),schemaVersion:z.literal(2).default(2)});export type Account=z.infer<typeof accountSchema>;
export function migrate(data:any):Account{const d=JSON.parse(JSON.stringify(data));if(d.schemaVersion>2)throw Error('FUTURE');for(const b of d.profiles??[]){const p=b.profile;p.availableDays??=p.days;p.sessionsPerWeek??=p.days.length;p.weekStartsOn??=6;p.planHistory??=[{effectiveFrom:localDate(),days:[...p.days]}];}d.schemaVersion=2;return accountSchema.parse(d)}
// Optional restState keeps old envelopes readable without rewriting historical sessions.
export function sessionRest(s:Session){if(s.finishedAt)return null;if(s.restState)return s.restState;const last=s.sets.at(-1);if(!last)return null;const totalSeconds=s.slots.find(x=>x.key===last.slotKey)?.rest??0;const deadline=Date.parse(last.at)+totalSeconds*1000;return Number.isFinite(deadline)&&deadline>=0?{deadline,totalSeconds}:null}
export function transitionInjury(injuries:Profile['injuries'],area:Area,status:Profile['injuries'][number]['status'],at=new Date().toISOString()):Profile['injuries']{const existing=injuries.find(i=>i.area===area);if(existing?.status===status)return injuries;const next=existing?{...existing,status,reviewed:false,history:[...existing.history,{status,at}]}:{area,status,reportedAt:localDate(new Date(at)),reviewed:false,history:[{status,at}]};return existing?injuries.map(i=>i.area===area?next:i):[...injuries,next]}
export function ageAt(date:string,ref=new Date()){const d=new Date(date+'T00:00:00');if(!date||!Number.isFinite(+d))return 0;let a=ref.getFullYear()-d.getFullYear();if(ref.getMonth()<d.getMonth()||(ref.getMonth()===d.getMonth()&&ref.getDate()<d.getDate()))a--;return a}
export const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export const normalize=(s:string)=>s.toLowerCase().normalize('NFKD').replace(/[\u064b-\u065f]/g,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[^\p{L}\p{N}]/gu,'');
export const searchExercises=(q:string)=>exercises.filter(e=>[e.ar,e.en,...e.aliases??[]].some(v=>normalize(v).includes(normalize(q))));
export const activeGym=(p:Profile)=>p.gyms.find(g=>g.id===p.activeGymId);
export const safeMode=(p:Profile)=>p.health!=='none'||p.injuries.some(i=>i.status!=='recovered');
export function eligible(e:Exercise,p:Profile){const g=activeGym(p);const eqs=g?.equipment??p.equipment;if(e.eq!=='body'&&!eqs.includes(e.eq as any))return false;if(g?.exact&&e.eq!=='body'&&!g.exerciseIds.includes(e.id))return false;if(p.dislikedExerciseIds.includes(e.id))return false;if(p.injuries.some(i=>i.status==='active'&&e.loadedAreas?.includes(i.area)))return false;if(p.injuries.some(i=>i.status==='improving'&&e.loadedAreas?.includes(i.area)&&(!i.reviewed||!['machine','cable'].includes(e.eq))))return false;return true}
export function alternatives(id:string,p:Profile){const e=byId[id];return e?exercises.filter(x=>x.id!==id&&x.group===e.group&&x.pattern===e.pattern&&eligible(x,p)).sort((a,b)=>score(b,p)-score(a,p)):[]}
function score(e:Exercise,p:Profile){return(p.preferredExerciseIds.includes(e.id)?20:0)+(safeMode(p)&&['machine','cable'].includes(e.eq)?8:0)+(e.eq==='machine'?2:0)}
export function chooseDays(available:number[],count:number,start=6){const a=[...new Set(available)].sort((x,y)=>(x-start+7)%7-(y-start+7)%7);if(count>a.length)throw Error('DAYS');let best:number[]=[],bestScore=-Infinity;for(let mask=0;mask<1<<a.length;mask++){const v=a.filter((_,i)=>mask>>i&1);if(v.length!==count)continue;const sorted=[...v].sort((x,y)=>x-y);const gaps=sorted.map((x,i)=>(sorted[(i+1)%sorted.length]-x+7)%7);const sc=gaps.reduce((s,g)=>s+Math.min(g,2)*10-(g-7/count)**2,0);if(sc>bestScore){best=v;bestScore=sc}}return best}
export function recommended(p:Profile|number):Profile['split']{if(typeof p==='number')return p<=3?'full':p<=5?'upper':'ppl';if(p.sessionsPerWeek<=3)return'full';if(p.goal==='strength'||p.experience!=='regular'||safeMode(p)||p.minutes<50)return'upper';return p.sessionsPerWeek===6?'ppl':'upper'}
export function reason(p:Profile,l:Lang){const s=recommended(p);return words(l,`${p.sessionsPerWeek} حصص × ${p.minutes} دقيقة، ${goals[p.goal][0]}، ${p.experience==='regular'?'خبرة منتظمة':'بداية أو رجوع'}${safeMode(p)?' مع قيود':''}: ${splits[s][0]} يوزّع الحمل على وقتك.`,`${p.sessionsPerWeek} sessions × ${p.minutes} min, ${goals[p.goal][1]}, ${p.experience}${safeMode(p)?', restrictions':''}: ${splits[s][1]} fits this workload.`)}
const patterns:Record<string,string[][]>={upper:[['push','row','vertical','lateral','triceps','biceps'],['knee','curl','hip','calf','core'],['incline','vertical','row','rear','biceps','triceps'],['knee','curl','hip','extension','calf','core']],ppl:[['push','incline','press','lateral','triceps'],['vertical','row','rear','biceps','core'],['knee','curl','hip','calf','core']],bro:[['push','incline','fly','triceps'],['vertical','row','rear','biceps'],['knee','curl','hip','calf','core'],['press','lateral','rear','biceps','triceps']],full:[['knee','push','row','hip','core'],['curl','incline','vertical','lateral','calf'],['knee','push','row','hip','biceps','triceps']],arnold:[['push','incline','vertical','row'],['press','lateral','biceps','triceps','rear'],['knee','curl','hip','calf','core']]};
const titles:Record<string,string[][]>={upper:[['علوي A','Upper A'],['سفلي A','Lower A'],['علوي B','Upper B'],['سفلي B','Lower B']],ppl:[['دفع','Push'],['سحب','Pull'],['رجل وبطن','Legs & core']],bro:[['صدر وتراي','Chest & triceps'],['ضهر وباي','Back & biceps'],['رجل وبطن','Legs & core'],['كتف ودراع','Shoulders & arms']],full:[['جسم كامل A','Full body A'],['جسم كامل B','Full body B'],['جسم كامل C','Full body C']],arnold:[['صدر وضهر','Chest & back'],['كتف ودراع','Shoulders & arms'],['رجل وبطن','Legs & core']]};
// MUST be reviewed by a qualified physiotherapist before release
// Candidate mapping only: disabled until the user's clinician reviews the relevant option.
export const injuryCardioMap:Record<Area,{candidates:string[];duration:[number,number];intensity:string;reviewed:boolean}>={shoulder:{candidates:['Bicycling_Stationary'],duration:[3,5],intensity:"easy, conversational pace",reviewed:false},elbow:{candidates:['Walking_Treadmill'],duration:[3,5],intensity:"easy, conversational pace",reviewed:false},back:{candidates:[],duration:[3,5],intensity:"easy, conversational pace",reviewed:false},hip:{candidates:[],duration:[3,5],intensity:"easy, conversational pace",reviewed:false},knee:{candidates:[],duration:[3,5],intensity:"easy, conversational pace",reviewed:false},ankle:{candidates:[],duration:[3,5],intensity:"easy, conversational pace",reviewed:false},neck:{candidates:[],duration:[3,5],intensity:"easy, conversational pace",reviewed:false}};
export type Block={id:string;kind:string;minutes:number;exId:string;optional:boolean};export type DayPlan={weekday:number;title:string;titleEn:string;slots:Slot[];minutes:number;warning:boolean;missing:string[];blocks:Block[];conservative:boolean};
export function restFor(e:Exercise,p:Profile){return safeMode(p)?Math.max(120,e.rest):p.goal==='strength'&&e.compound?180:p.goal==='endurance'?Math.max(60,Math.min(90,e.rest)):e.rest}
// Only inputs read by makePlan/eligible/score/restFor. Persistence reparses profiles,
// so reference identity alone would invalidate the plan after unrelated saves.
export function planInputKey(p:Profile|undefined){if(!p)return '';const gym=activeGym(p);return JSON.stringify([p.split,p.days,p.weekStartsOn,p.days.map(d=>p.dayMinutes[String(d)]??p.minutes),p.goal,p.secondaryGoals,p.priority,p.stage,p.health,p.urgentSymptoms,p.injuries.map(i=>[i.area,i.status,i.reviewed]),gym?.equipment??p.equipment,gym?.exact??false,gym?.exact?gym.exerciseIds:[],p.preferredExerciseIds,p.dislikedExerciseIds])}
export function makePlan(p:Profile):DayPlan[]{const chosen=patterns[p.split];const used=new Set<string>();return [...p.days].sort((a,b)=>(a-p.weekStartsOn+7)%7-(b-p.weekStartsOn+7)%7).map((weekday,i)=>{const minutes=p.dayMinutes[String(weekday)]??p.minutes;const safe=safeMode(p);let pats=[...chosen[i%chosen.length]];if(p.split==='upper'&&p.days.length===5&&i===4)pats=['push','row','knee','curl','core'];if(p.split==='bro'&&p.days.length===3&&i===0)pats.push('lateral');const slots:Slot[]=[];const missing:string[]=[];if(!p.urgentSymptoms)for(const pat of pats){const opts=exercises.filter(e=>e.pattern===pat&&eligible(e,p)).sort((a,b)=>score(b,p)-score(a,p)+(used.has(a.id)?5:0)-(used.has(b.id)?5:0));const e=opts[0];if(!e){missing.push(pat);continue}used.add(e.id);const strength=p.goal==='strength'&&e.compound;slots.push({key:`d${weekday}-s${slots.length}`,exId:e.id,sets:safe?1:p.stage===2?3:2,low:e.mode==='seconds'?15:safe?10:strength?5:p.goal==='endurance'?12:e.reps[0],high:e.mode==='seconds'?30:safe?12:strength?8:p.goal==='endurance'?18:e.reps[1],rest:restFor(e,p)})}
if(p.priority!=='balanced')slots.sort((a,b)=>Number(byId[b.exId].group===p.priority)-Number(byId[a.exId].group===p.priority));
const blocks:Block[]=[];const allGoals=[p.goal,...p.secondaryGoals];if(!p.urgentSymptoms&&!safe&&allGoals.some(g=>['loss','fitness','endurance'].includes(g))){const candidates=exercises.filter(e=>e.group==='cardio'&&eligible(e,p));const e=candidates[i%candidates.length];if(e)blocks.push({id:'cardio',kind:'cardio',minutes:Math.min(minutes<45?6:12,p.goal==='loss'?12:p.goal==='endurance'?10:8),exId:e.id,optional:false});else missing.push('cardio')}
if(!p.urgentSymptoms&&!safe&&allGoals.includes('mobility')){const candidates=exercises.filter(e=>e.group==='mobility'&&eligible(e,p));if(candidates.length)for(let j=0;j<Math.min(2,candidates.length);j++)blocks.push({id:'mobility-'+j,kind:'mobility',minutes:3,exId:candidates[(i*2+j)%candidates.length].id,optional:false});else missing.push('mobility')}
let estimate=()=>Math.ceil(5+blocks.reduce((n,b)=>n+b.minutes,0)+slots.reduce((n,s)=>n+s.sets*.75+(s.sets-1)*s.rest/60+1.25,0));while(estimate()>minutes&&slots.some(s=>s.sets>2)){slots.findLast(s=>s.sets>2)!.sets--}while(estimate()>minutes&&slots.length>1){slots.pop()}
const title=titles[p.split][i%titles[p.split].length];return{weekday,title:title[0],titleEn:title[1],slots,blocks,minutes:estimate(),warning:!slots.length,missing,conservative:safe}})}
export function nutrition(p:Profile){if(!p.nutritionEnabled||p.health==='medical'||p.health==='unknown')return null;const bmi=p.weight/(p.height/100)**2;if(bmi<18.5&&p.goal==='loss')return null;const age=p.birthDate?ageAt(p.birthDate):p.age;const rest=10*p.weight+6.25*p.height-5*age+(p.sex==='male'?5:p.sex==='female'?-161:-78);const factor=p.activity==='low'?1.4:p.activity==='moderate'?1.6:1.8;const maintenance=rest*factor;const multiplier=p.goal==='loss'?.85:['weight','muscle'].includes(p.goal)?1.1:1;const target=Math.round(maintenance*multiplier/25)*25;const protein=Math.round(p.weight*1.6);const fat=Math.round(target*.28/9);const carbs=Math.round((target-4*protein-9*fat)/4);return carbs>=0?{bmi,rest:Math.round(rest),factor,maintenance:Math.round(maintenance),target,protein,fat,carbs,multiplier,rough:p.sex==='unspecified'}:null}
export const safeFileName=(s:string)=>s.replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,60)||'profile';
export function e1rm(s:LoggedSet){const e=byId[s.exId];return e&&!e.assisted&&e.mode==='reps'&&e.unit!=='body'&&s.weight>0&&s.reps<=12?s.weight*(1+s.reps/30):null}
export function exerciseTrend(b:Bundle,id:string){return b.sessions.filter(s=>s.finishedAt).map(s=>{const a=s.sets.filter(x=>x.exId===id);return{date:s.date,gymId:s.gymId,sets:a,weight:a.length?Math.max(...a.map(x=>x.weight)):0,rm:Math.max(0,...a.map(x=>e1rm(x)??0)),reps:a.length?Math.max(...a.map(x=>x.reps)):0}}).filter(x=>x.sets.length)}
export function prTypes(s:LoggedSet,previous:LoggedSet[]){const e=byId[s.exId];if(!e||e.mode!=='reps'||e.assisted)return[];const old=previous.filter(x=>x.exId===s.exId&&x.gymId===s.gymId);if(!old.length)return['baseline'];const r:string[]=[];if(s.weight>Math.max(...old.map(x=>x.weight)))r.push('weight');const same=old.filter(x=>x.weight===s.weight);if(same.length&&s.reps>Math.max(...same.map(x=>x.reps)))r.push('reps');const rm=e1rm(s);if(rm&&rm>Math.max(...old.map(x=>e1rm(x)??0)))r.push('rm');return r}
// Same stored order and strict comparisons as prTypes, without rebuilding every
// prefix of the history. Active sessions also count, as they did in Progress.
export function prHistory(sessions:Session[]){
 const records=new Map<string,Map<string,{weight:number;rm:number;reps:Map<number,number>}>>();
 const badges:{kind:string;id:string;exId:string;date:string}[]=[];
 for(const session of sessions)for(const set of session.sets){
  const e=byId[set.exId];if(!e||e.mode!=='reps'||e.assisted)continue;
  let gyms=records.get(set.exId);if(!gyms){gyms=new Map();records.set(set.exId,gyms)}
  const old=gyms.get(set.gymId),rm=e1rm(set)??0;
  if(old){
   const add=(kind:string)=>badges.push({kind,id:set.id,exId:set.exId,date:session.date});
   if(set.weight>old.weight)add('weight');
   const reps=old.reps.get(set.weight);if(reps!==undefined&&set.reps>reps)add('reps');
   if(rm&&rm>old.rm)add('rm');
   old.weight=Math.max(old.weight,set.weight);old.rm=Math.max(old.rm,rm);
   old.reps.set(set.weight,Math.max(reps??0,set.reps));
  }else gyms.set(set.gymId,{weight:set.weight,rm,reps:new Map([[set.weight,set.reps]])});
 }
 return badges;
}
export function progression(exId:string,b:Bundle){return !!loadAdvice(exId,b).increase}
export function loadAdvice(id:string,b:Bundle){const p=b.profile,e=byId[id],g=activeGym(p);const recent=b.sessions.filter(s=>s.finishedAt&&s.gymId===(g?.id??'')&&s.sets.some(x=>x.exId===id)).slice(-3);const last=recent.at(-1);if(!last||!e)return{increase:false,next:null,plateau:false};const sets=last.sets.filter(x=>x.exId===id);const base=sets.at(-1)!.weight;const top=recent.slice(-2);const qualifies=top.length===2&&top.every(s=>{const slot=s.slots.find(x=>x.exId===id);const xs=s.sets.filter(x=>x.exId===id);return slot&&xs.length>=slot.sets&&xs.every(x=>x.reps>=slot.high&&x.rir>=2)&&!Object.values(s.painByArea).some(v=>v>0)});const increase=qualifies&&!safeMode(p)&&e.unit!=='body'&&!e.assisted;let jump=e.group==='legs'?p.lowerIncrement:p.upperIncrement;jump=Math.min(jump,Math.max(.25,base*.05));const next=increase?Math.round((base+jump)*4)/4:null;
const comparable=recent.length===3&&recent.every(s=>{const sl=s.slots.find(x=>x.exId===id),ref=last.slots.find(x=>x.exId===id);return sl&&ref&&sl.low===ref.low&&sl.high===ref.high&&sl.sets===ref.sets&&s.goalSnapshot===last.goalSnapshot&&s.sets.filter(x=>x.exId===id).length>=sl.sets});const vals=recent.map(s=>Math.max(...s.sets.filter(x=>x.exId===id).map(x=>x.weight*(1+x.reps/30))));const plateau=comparable&&vals[2]<=vals[1]&&vals[1]<=vals[0];return{increase,next,plateau}}
export function weekStart(date=new Date(),start=6){const d=new Date(date);d.setHours(0,0,0,0);d.setDate(d.getDate()-(d.getDay()-start+7)%7);return d}
export function weeklyVolume(b:Bundle,date=new Date()){const start=+weekStart(date,b.profile.weekStartsOn),end=start+7*86400000;const sums=Object.fromEntries(Object.keys(groups).map(k=>[k,0]));for(const s of b.sessions)if(+new Date(s.date)>=start&&+new Date(s.date)<end)for(const x of s.sets){const e=byId[x.exId];if(e&&x.rir<=3&&e.group!=='cardio'&&e.group!=='mobility')sums[e.group]++}return sums}
export function adherence(b:Bundle,now=new Date()){return[3,2,1,0].map(w=>{const start=weekStart(now,b.profile.weekStartsOn);start.setDate(start.getDate()-7*w);let planned=0,done=0;for(let i=0;i<7;i++){const d=new Date(start);d.setDate(d.getDate()+i);if(d>now)continue;const key=localDate(d);const h=b.profile.planHistory.filter(h=>h.effectiveFrom<=key).at(-1);if(h?.days.includes(d.getDay()))planned++;if(b.sessions.some(s=>s.date===key&&s.finishedAt))done++}return{date:localDate(start),planned,done,percent:planned?Math.min(100,Math.round(done/planned*100)):null}})}
export function comebackDeadline(b:Bundle){const last=b.sessions.filter(s=>s.finishedAt).at(-1);if(!last)return null;for(let n=1;n<=14;n++){const d=new Date(last.date+'T12:00:00');d.setDate(d.getDate()+n);if(b.profile.days.includes(d.getDay())&&!b.sessions.some(s=>s.finishedAt&&s.date===localDate(d)))return +d+4*86400000}return null}
export function comebackDue(b:Bundle,now=new Date()){if(b.profile.comebackDismissed===localDate(now))return false;const deadline=comebackDeadline(b);return deadline!==null&&+now>=deadline}
export function plateTotal(bar:number,plates:{kg:number;pairs:number}[]){return bar+2*plates.reduce((n,p)=>n+p.kg*p.pairs,0)}
export function plateSolve(target:number,bar:number,plates:{kg:number;pairs:number}[]){if(target<bar)return{total:bar,plates:[],exact:false};const max=Math.round((target-bar)*50);let states=new Map<number,{kg:number;pairs:number}[]>([[0,[]]]);for(const p of [...plates].sort((a,b)=>b.kg-a.kg)){const next=new Map(states);for(const [n,list]of states)for(let c=1;c<=p.pairs;c++){const k=n+Math.round(p.kg*100)*c;if(k<=max&&!next.has(k))next.set(k,[...list,{kg:p.kg,pairs:c}])}states=next}const best=Math.max(...states.keys());return{total:bar+best/50,plates:states.get(best)!,exact:Math.abs(bar+best/50-target)<.001}}
